##============================================================================
##  Copyright (c) Kitware, Inc.
##  All rights reserved.
##  See LICENSE.txt for details.
##
##  This software is distributed WITHOUT ANY WARRANTY; without even
##  the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
##  PURPOSE.  See the above copyright notice for more information.
##============================================================================

# This file is automatically generated by CMake, do not edit.
VTKm_VERSION = 2.2
VTKm_DIR = /ucrt64

VTKm_BUILD_SHARED_LIBS = ON
VTKm_ENABLE_CUDA = OFF
VTKm_ENABLE_KOKKOS = OFF
VTKm_ENABLE_OPENMP = ON
VTKm_ENABLE_TBB = ON
VTKm_ENABLE_LOGGING = ON
VTKm_ENABLE_RENDERING = OFF
VTKm_ENABLE_GL_CONTEXT = 
VTKm_ENABLE_OSMESA_CONTEXT = 
VTKm_ENABLE_EGL_CONTEXT = 
VTKm_ENABLE_MPI = OFF

VTKm_INCLUDE_DIR = $(VTKm_DIR)/include/vtkm-2.2
VTKm_INCLUDE_FLAGS = -I$(VTKm_INCLUDE_DIR) -I$(VTKm_INCLUDE_DIR)/vtkm/thirdparty/diy/vtkmdiy/include/ -I$(VTKm_INCLUDE_DIR)/vtkm/thirdparty/lcl/vtkmlcl/

VTKm_LIB_FLAGS = -L $(VTKm_DIR)/lib \
    -lvtkm_source-2.2 \
    -lvtkm_io-2.2 \
    -lvtkm_filter_zfp-2.2 \
    -lvtkm_filter_uncertainty-2.2 \
    -lvtkm_filter_scalar_topology-2.2 \
    -lvtkm_filter_resampling-2.2 \
    -lvtkm_filter_image_processing-2.2 \
    -lvtkm_filter_flow-2.2 \
    -lvtkm_filter_field_transform-2.2 \
    -lvtkm_filter_field_conversion-2.2 \
    -lvtkm_filter_entity_extraction-2.2 \
    -lvtkm_filter_density_estimate-2.2 \
    -lvtkm_filter_geometry_refinement-2.2 \
    -lvtkm_filter_contour-2.2 \
    -lvtkm_filter_multi_block-2.2 \
    -lvtkm_filter_mesh_info-2.2 \
    -lvtkm_filter_vector_analysis-2.2 \
    -lvtkm_filter_connected_components-2.2 \
    -lvtkm_filter_clean_grid-2.2 \
    -lvtkm_filter_core-2.2 \
    -lvtkm_worklet-2.2 \
    -lvtkm_cont_testing-2.2 \
    -lvtkm_cont-2.2 \
    -lvtkmdiympi_nompi
